### ISSUE TITLE
Problem when using MIME enconding

### ISSUE THREAD

**Issue by kantale** [kantale/biol-494#2]
In this commit: c9aecb3
From this PL: https://github.com/kantale/biol-494/pull/1 

it was introduced a change to "Correct MIME encoding issues".
When I am using this code, the text appears as an attachment named: ```noname```. 
Screenshot:
<img width="466" alt="image" src="https://user-images.githubusercontent.com/1254711/113290765-c2a4ed80-92fa-11eb-896c-6a495695ed50.png">

When I am using the "old" method ```message = 'Subject: {}\n\n{}'.format(subject, text)``` 

The message appears normal in the mail..
 I have no idea why it appears as an attachment when using this code:
```python
        msg = MIMEText(text, 'utf-8')
        sender_email = "alexandros.kanterakis@gmail.com"
        receiver_email = to
        msg['From'] = sender_email # Hopefully no utf8 weirdness here...
        msg['To'] = receiver_email
        msg['Subject'] = Header(subject, 'utf-8')
        message = msg.as_string()

       self.server.sendmail(sender_email, receiver_email, message.encode("utf-8"))
```

An appears normal when using this code:
```python
message = 'Subject: {}\n\n{}'.format(subject, text)
self.server.sendmail(sender_email, receiver_email, message.encode("utf-8"))
```

Any idea?

**Comment by irtzonevrakis** [comment]
Perhaps adding
`msg['Content-type'] = 'text/plain; charset=utf-8'`
to explicitly tell gmail what to expect will alleviate the problem?

**Comment by irtzonevrakis** [comment]
The proposed fix works on the university's SMTP server, so it should work on g-mail's, too.
With Content-type header:
![image](https://user-images.githubusercontent.com/80422873/113298837-e836f480-9304-11eb-8515-a7237b397241.png)
Without Content-type header:
![image](https://user-images.githubusercontent.com/80422873/113298896-fab12e00-9304-11eb-88e6-1d13aca6442a.png)

**Comment by irtzonevrakis** [comment]
...PR sent

https://github.com/kantale/biol-494/pull/3

**Comment by irtzonevrakis** [comment]
## Detailed explanation of the reasoning behind the changes in the PR
Gmail's webmail probably expects single-part text/plain to be encoded as quoted-printable. However, python3 cannot pass utf-8 to the mail server (see https://bugs.python.org/issue25736), and, as such has to encode the e-mail as base64. However, gmail's webmail [and possibly other mail user agents, including the biology department's roundcube webmail, but not thunderbird, where I did my testing on before sending the PR] sees the bare base64 in the message, and, possibly, as part of a mitigation to some user agent's bug, interprets it as an attachment. To avoid this, the base64-encoded text has to be attached as text/plain to a mime/multipart message before sending it.
